var nuevo= $("html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._n_n3 div.conductorContent div#primaryContainer._n_e div div.conductorContent div._n_T div._n_X div._n_X div._n_X div._n_r1 div._n_s1 div._fce_a.ms-bg-color-themeLighterAlt div._fce_b div._fce_c div._fce_e.ms-bgc-tlr-h button._fce_h._fce_f.ms-fwt-r.ms-fcl-np.o365button");
nuevo.click();
//dejar tiempo de carga
var para= $("html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._n_n3 div.conductorContent div#primaryContainer._n_e div div.conductorContent div._n_T div._n_X div._n_X div div._n_X div._n_Y div.allowTextSelection div.conductorContent div._mcp_U2._mcp_X2 div._mcp_V2._mcp_X2.scrollContainer._mcp_Z2 div._mcp_a3 div._mcp_d1.ms-border-color-neutralLight div._mcp_e1.ms-bg-color-white div div._mcp_f1 div.ms-bg-color-white.customScrollBar.ms-border-color-themeTertiary div div._mcp_o1 div._mcp_L1._mcp_M1._mcp_B1 div._mcp_c2 div._rw_u div._rw_u.allowTextSelection span.findControlWrapper div._fp_F form input._fp_G.ms-fwt-r.ms-font-color-neutralSecondary.allowTextSelection.ms-bgc-nl.textbox.ms-font-s.ms-fwt-sl.ms-fcl-np.ms-bcl-nta.ms-bcl-nsa-h.hideClearButton.ms-fcl-ns");
var titulo= $("html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._n_n3 div.conductorContent div#primaryContainer._n_e div div.conductorContent div._n_T div._n_X div._n_X div div._n_X div._n_Y div.allowTextSelection div.conductorContent div._mcp_U2._mcp_X2 div._mcp_V2._mcp_X2.scrollContainer._mcp_Z2 div._mcp_a3 div._mcp_d1.ms-border-color-neutralLight div._mcp_e1.ms-bg-color-white div div._mcp_f1 div.ms-bg-color-white.customScrollBar.ms-border-color-themeTertiary div div._mcp_o1._mcp_r1._mcp_x1.ms-border-color-neutralTertiaryAlt div._mcp_c2 div input._mcp_Q1._mcp_R1.ms-font-weight-regular.ms-bg-color-white-hover.ms-font-color-neutralPrimary.allowTextSelection.textbox.ms-font-s.ms-fwt-sl.ms-fcl-np.ms-bcl-nta.ms-bcl-nsa-h");
var contenido= $("html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._n_n3 div.conductorContent div#primaryContainer._n_e div div.conductorContent div._n_T div._n_X div._n_X div div._n_X div._n_Y div.allowTextSelection div.conductorContent div._mcp_U2._mcp_X2 div._mcp_V2._mcp_X2.scrollContainer._mcp_Z2 div._mcp_a3 div._mcp_d1.ms-border-color-neutralLight div._mcp_e1.ms-bg-color-white div div._mcp_z1.ms-border-color-neutralTertiary-hover.ms-border-color-neutralTertiaryAlt div._mcp_22 div div._z_41.ms-bg-color-white div div div.allowTextSelection._mcp_32.customScrollBar.ms-bg-color-white.ms-font-color-black.owa-font-compose");
var enviar= $("html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._n_n3 div.conductorContent div#primaryContainer._n_e div div.conductorContent div._n_T div._n_X div._n_X div div._n_X div._n_Y div.allowTextSelection div.conductorContent div._mcp_U2._mcp_X2 div._mcp_V2._mcp_X2.scrollContainer._mcp_Z2 div._mcp_a3 div._mcp_d1.ms-border-color-neutralLight div._mcp_e1.ms-bg-color-white div._mcp_g1._mcp_x1.ms-bg-color-white.ms-border-color-neutralTertiaryAlt div._mcp_i1 div._mcp_I2 button._mcp_62.o365button.o365buttonOutlined.ms-font-m.ms-fwt-sb.ms-fcl-w.ms-bgc-tp.ms-bcl-tp.ms-bgc-td-f.ms-bcl-tdr-f");
var contacto = $('html body.notIE8.ms-fwt-r.customScrollBar.firefox.disableTextSelection.mainWindow.removeFocusOutline div._fp_7 div div._fp_b.ms-bg-color-white._fp_c div._fp_e.scrollContainer div.searchHitHighlightConvergence._fp_w div._fp_v.ms-border-color-neutralTertiary div._fp_n.ms-border-color-neutralLight div._fp_Y');
para.val("jma.lovera10@uniandes.edu.co");
titulo.click();
titulo.focus();
titulo.val("boteando");
enviar.click();